# Generated by tools/release.sh tap from packaging/homebrew/macmeow.rb in
# https://github.com/xlanstar/mac-meow. Do not edit in the tap; change the template instead.
cask "macmeow" do
  version "@VERSION@"
  sha256 "@SHA256@"

  url "https://github.com/xlanstar/mac-meow/releases/download/v#{version}/MacMeow-#{version}.dmg"
  name "MacMeow"
  name "貓貓谷 for Mac"
  desc "Launcher for the MeowMS MapleStory private server via Cyder"
  homepage "https://github.com/xlanstar/mac-meow"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "MacMeow.app"

  uninstall quit: "tw.macmeow.launcher"

  zap launchctl: "tw.macmeow.loopback",
      delete:    "/Library/LaunchDaemons/tw.macmeow.loopback.plist",
      trash:     [
        "~/Library/Application Support/MacMeow",
        "~/Library/Caches/MacMeow",
        "~/Library/Logs/MacMeow",
        "~/Library/Preferences/tw.macmeow.launcher.plist",
        "~/Library/Saved Application State/tw.macmeow.launcher.savedState",
      ]

  caveats <<~EOS
    MacMeow 需要 Cyder（x86_64 Wine，需要 Rosetta 2）：
      https://github.com/dspp779/CyderBits/releases

    移除前請先依 README「移除」還原 Cyder engine 的修補：
      https://github.com/xlanstar/mac-meow#移除
  EOS
end
