# Generated by tools/release.sh tap from packaging/homebrew/macmeow.rb in
# https://github.com/xlanstar/mac-meow. Do not edit in the tap; change the template instead.
cask "macmeow" do
  version "@VERSION@"
  sha256 "@SHA256@"

  url "https://github.com/xlanstar/mac-meow/releases/download/v#{version}/MacMeow-#{version}.dmg"
  name "MacMeow"
  name "貓貓谷 for Mac"
  desc "Launcher for the MeowMS MapleStory private server via Cyder"
  homepage "https://github.com/xlanstar/mac-meow"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "MacMeow.app"

  # App 移到 appdir 之前，把 App 內的 scripts 複製到 Caskroom（staged_path）。uninstall 區塊執行這一份，
  # 使用者自行刪除 App 後 brew uninstall 仍能還原修補與設定。
  preflight_steps do
    copy "MacMeow.app/Contents/Resources/scripts", "scripts", recursive: true
  end

  # quit 先於 script：App 結束後才刪除它的設定。brew upgrade／reinstall 也會執行這個區塊，
  # 這時 uninstall.sh cask 什麼都不做（見 scripts/uninstall.sh）。相對路徑以 staged_path 解析。
  uninstall quit:   "tw.macmeow.launcher",
            script: {
              executable: "scripts/uninstall.sh",
              args:       ["cask"],
            }

  zap launchctl: "tw.macmeow.loopback",
      delete:    "/Library/LaunchDaemons/tw.macmeow.loopback.plist",
      trash:     [
        "~/Library/Application Support/MacMeow",
        "~/Library/Caches/MacMeow",
        "~/Library/Logs/MacMeow",
        "~/Library/Preferences/tw.macmeow.launcher.plist",
        "~/Library/Saved Application State/tw.macmeow.launcher.savedState",
      ]

  caveats <<~EOS
    MacMeow 需要 Cyder（x86_64 Wine，需要 Rosetta 2）：
      https://github.com/dspp779/CyderBits/releases

    brew uninstall --cask macmeow 會還原 Cyder engine 的修補與 Cyder 設定、
    加回遊戲資料夾的下載隔離標記、移除本機網路位址（需要密碼），
    以及 App 的設定與記錄。
  EOS
end
